/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Data.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Peter
 */
public class SearchBox extends javax.swing.JInternalFrame {

    /**
     * Creates new form searchBox
     */
    public SearchBox(MainWindow parent) {

        initComponents();

        List<Card> results = new ArrayList<>();

        this.searchField.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    String searchQuery = getQuery();
                    for (Card p : Deck.returnPersonCards()) {
                        if (p.getName().toLowerCase().contains(searchQuery.toLowerCase())) {
                            System.out.println(p);
                            results.add(p);
                        }
                    }
                    if (results.isEmpty()) {
                        dispose();
                    }
                    else if (results.size() == 1) {
                        CharacterCreator cc = new CharacterCreator(parent, results.get(0));
                        cc.setVisible(true);
                        parent.getDesktop().add(cc);
                        parent.select(cc);
                        parent.disposable(cc);
                        dispose();
                    } else if(results.size() >= 1) {
                        CharacterList resultList = new CharacterList(parent, results);
                        resultList.setVisible(true);
                        parent.getDesktop().add(resultList);
                        parent.select(resultList);
                        parent.disposable(resultList);
                        dispose();
                    }
                }
            }
        });
    }

    public String getQuery() {
        return this.searchField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
